---
root: true
env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier:
    - error
  func-names:
    - warn
    - as-needed
  no-console: 0
  no-shadow: 0
  consistent-return: 0
  no-const-assign: warn
  no-plusplus: 0
  no-this-before-super: warn
  no-undef: warn
  no-unreachable: warn
  no-unused-vars: warn
  constructor-super: warn
  valid-typeof: warn
